---
HOSTS:
  centos-7-x64:
    platform: el-7-x64
    box: puppetlabs/centos-7.0-64-nocm
    hypervisor: vagrant
    pe_ver: '2016.4'
    roles:
      - agent
CONFIG:
  log_level: verbose
  type: foss
ssh:
  password: root
  auth_methods: ["password"]
